"""stream thumbnail_url

Revision ID: 75346eea8c38
Revises: d75533cf955a
Create Date: 2025-12-01 17:13:19.112021

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa F401
import sqlmodel

from alembic import op  # noqa F401

# revision identifiers, used by Alembic.
revision: str = "75346eea8c38"
down_revision: Union[str, Sequence[str], None] = "d75533cf955a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "streams",
        sa.Column("thumbnail_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("streams", "thunbnail_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "streams",
        sa.Column("thunbnail_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("streams", "thumbnail_url")
    # ### end Alembic commands ###
