"""Fix datetime defaults

Revision ID: c3ddd72c1b24
Revises: 203f0356148e
Create Date: 2025-11-22 04:18:32.786368

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "c3ddd72c1b24"
down_revision: Union[str, Sequence[str], None] = "203f0356148e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
