"""Change roles to role

Revision ID: cd43ad291612
Revises: c3ddd72c1b24
Create Date: 2025-11-22 08:02:33.598206

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "cd43ad291612"
down_revision: Union[str, Sequence[str], None] = "c3ddd72c1b24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.VARCHAR(), nullable=True))
    op.alter_column(
        "users",
        "reset_token_expires_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.drop_column("users", "roles")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("roles", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "reset_token_expires_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_column("users", "role")
    # ### end Alembic commands ###
