"""streams model

Revision ID: d75533cf955a
Revises: bb925a92aa3c
Create Date: 2025-11-26 11:20:22.854643

"""

from typing import Sequence, Union

import sqlalchemy as sa  # noqa F401
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op  # noqa F401

# revision identifiers, used by Alembic.
revision: str = "d75533cf955a"
down_revision: Union[str, Sequence[str], None] = "bb925a92aa3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "streams",
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("category", sa.VARCHAR(), nullable=True),
        sa.Column("thunbnail_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "stream_key", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "rtmp_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column(
            "hls_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("is_live", sa.Boolean(), nullable=False),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("current_viewers", sa.Integer(), nullable=False),
        sa.Column("total_views", sa.Integer(), nullable=False),
        sa.Column("peak_viewers", sa.Integer(), nullable=False),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("ended_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("sid", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("sid"),
    )
    op.create_index(op.f("ix_streams_sid"), "streams", ["sid"], unique=False)
    op.create_index(
        op.f("ix_streams_stream_key"), "streams", ["stream_key"], unique=True
    )
    op.create_index(op.f("ix_streams_title"), "streams", ["title"], unique=False)
    op.create_index(op.f("ix_streams_user_id"), "streams", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_streams_user_id"), table_name="streams")
    op.drop_index(op.f("ix_streams_title"), table_name="streams")
    op.drop_index(op.f("ix_streams_stream_key"), table_name="streams")
    op.drop_index(op.f("ix_streams_sid"), table_name="streams")
    op.drop_table("streams")
    # ### end Alembic commands ###
