"""change role from list to str

Revision ID: ea39c99bf263
Revises: cd43ad291612
Create Date: 2025-11-24 19:15:24.848623

"""

from typing import Sequence, Union

# import sqlalchemy as sa  # noqa: F401

# from alembic import op # noqa: F401

# revision identifiers, used by Alembic.
revision: str = "ea39c99bf263"
down_revision: Union[str, Sequence[str], None] = "cd43ad291612"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
